services:
  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    container_name: quarkus_service
    depends_on:
      - database
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/finance_db
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  pg_data:
